### ISSUE TITLE
Bug with Litebans

### ISSUE THREAD

**Issue by belphegorspn** [Spicord/BanAnnouncer#100]
Can't forward messages to discord after updating LiteBans.
"In the LiteBans 2.10 update, I updated the MySQL driver from version 8.0.18 => 8.0.29, and they changed the default behaviour of a certain method which causes the bug" - litebans developer

https://paste.gg/p/anonymous/b05a592eda5a4ce989d5a601374bf92c

**Comment by anvorgesa** [comment]
Reading issue history is not a bad idea.
https://github.com/Spicord/BanAnnouncer/issues/94#issuecomment-1200024631
