### ISSUE TITLE
ignore-silent not working with advancedban

### ISSUE THREAD

**Issue by LPSebi** [Spicord/BanAnnouncer#101]

**Comment by LPSebi** [comment]
It still sends to the discord when its set to true

**Comment by anvorgesa** [comment]
The config says that option is for LiteBans, not AdvancedBan.

**Comment by LPSebi** [comment]
Would it be possible to implement that for advancedbans?

**Comment by anvorgesa** [comment]
Unfortunately not, as AdvancedBan does not provides a way to check if a punishment was made with the silent option.

**Comment by LPSebi** [comment]
Is it not possible to just check if the first/second argument of the command -s is?

**Comment by anvorgesa** [comment]
BanAnnouncer does not process or intercepts commands of any plugin, it uses the plugin's API to get the information.

**Comment by LPSebi** [comment]
could you take a look at this PR? I'm not sure if its the right thing... https://github.com/DevLeoko/AdvancedBan/pull/523

**Comment by anvorgesa** [comment]
That PR was made by me, but there hasn't been an AdvancedBan update since 2020 so that code is not actually included into any AB release.

**Comment by LPSebi** [comment]
Is there any way it could be implemented?

**Comment by anvorgesa** [comment]
It is already merged, but since there hasn't been any new release then that code is not yet into any AB .jar

**Comment by LPSebi** [comment]
Is it possible to do something to speed up the "release" or to do anything?
Maybe write the dev?

**Comment by anvorgesa** [comment]
There's no AdvancedBan release planned anytime soon. Maybe in another year or two. :thinking:

**Comment by LPSebi** [comment]
Hmmm... can we do anything about that?

**Comment by anvorgesa** [comment]
Nope

**Comment by LPSebi** [comment]
Not even compiling the plugin ourselves?

**Comment by LPSebi** [comment]
Hmm.. that's a bummer.
