### ISSUE TITLE
Error with announcing a punishment 2

### ISSUE THREAD

**Issue by CaptainRexPL** [Spicord/BanAnnouncer#109]
When I use /ban, /unban or any advancedban command used for punishing instead I get this error:
WARN  BanAnnouncer] BanAnnouncer does not have access to an active bot.
I added the a comma where it was missing, but it still doesn't work.

**Comment by CaptainRexPL** [comment]
plugins installed on the server: AdvancedBan, AdvancedReplay*, AntiCheatReplay, AuctionHouse, AuthMe, BanAnnouncer, BeautyQuests, CCTV, ChatManager, Chunky, ChunkyBorder, Citizens, CoreProtect, DecentHolograms, DiscordSRV, dtlTraders, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, GrimAC, ImageOnMap, InventoryRollbackPlus, LuckPerms, Multiverse-Core, MythicMobs, NexEngine, NoChatReports, OreAnnouncer, PlaceholderAPI, ProtocolLib, Retribution, Sentinel, SkinsRestorer, spark, Spicord, SuperVanish, TAB, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard

**Comment by anvorgesa** [comment]
No need to create new issues
