### ISSUE TITLE
An error using the new version of litebans:

### ISSUE THREAD

**Issue by thiagogebrimm** [Spicord/BanAnnouncer#110]
![image](https://user-images.githubusercontent.com/75040244/211899143-95c92b32-4871-4148-b8f5-b8a8ccd357a7.png)

**Comment by anvorgesa** [comment]
Hi, sorry for the delayed response, the error doesn't seem to be related with LiteBans at all but with another plugin that also implements a Discord functionality that causes an incompatibility issue with BA
