### ISSUE TITLE
Can I ask you a question

### ISSUE THREAD

**Issue by SmallBugDragon** [Spicord/BanAnnouncer#119]
I want a variable plugin that supports BungeCord and Litebans variables. Can you give me a suggestion？Thank You very much

**Comment by anvorgesa** [comment]
I don't know what do you mean by "variables"

**Comment by SmallBugDragon** [comment]
placeholderapi

**Comment by SmallBugDragon** [comment]
I'm sorry to use translation software to communicate with you.

**Comment by anvorgesa** [comment]
I don't know any plugin that does what you asked, sorry
