### ISSUE TITLE
AdvancedBan no support

### ISSUE THREAD

**Issue by JuraRusan** [Spicord/BanAnnouncer#121]
Hello! I'm using the AdvancedBan version of Velocity (https://github.com/DevLeoko/AdvancedBan/pull/641), but I'm running into a problem: BanAnnouncer doesn't know what AdvancedBan is. Can you help?

log - https://paste.helpch.at/tufeqayube.log
config - https://paste.helpch.at/cebekirusu.yaml
embeds - default

Thanks in advance!

**Comment by anvorgesa** [comment]
There is no **official** AdvancedBan release with Velocity support apart from the dev build you are likely using. BanAnnouncer only supports official plugin releases.
