### ISSUE TITLE
Spicord not detecting addon

### ISSUE THREAD

**Issue by AnjanPlayz** [Spicord/BanAnnouncer#29]
I followed the instructions about setting up the plugin, but later this happens

"21:51:00 [WARNING] [Spicord] The addon with the id 'ban_announcer' was not found."
"21:51:00 [WARNING] [Spicord] The addon with the id 'daily_statistics' was not found."

**Comment by OopsieWoopsie** [comment]
Make sure you have downloaded the .jar files for those addons and put them into your "plugins" folder.
