### ISSUE TITLE
Addon not found

### ISSUE THREAD

**Issue by mrmelk03** [Spicord/BanAnnouncer#31]
[WARNING] [Spicord] The addon with the id 'ban_announcer' was not found.

Any fix on this?

**Comment by mrmelk03** [comment]
https://pastebin.com/fBM2jFyb

**Comment by OopsieWoopsie** [comment]
When you edited the embed messages (the .json files) you broke its format, use this site https://leovoel.github.io/embed-visualizer/ to validate and edit your messages, otherwise you may still be breaking it.
