### ISSUE TITLE
BanAnnouncer doesn't work

### ISSUE THREAD

**Issue by HackerSte** [Spicord/BanAnnouncer#32]
The plugin worked until yesterday, but today I banned a person but the bot on Discord didn't announce it. I checked that the token hadn't changed, that Spicord was configured well, and that the bot had all permissions, but it still doesn't work. I have already tried to restart the server. I use Paper 1.15.2 on a BungeeCord (AdvancedBan uses a MySQL database)

**Comment by OopsieWoopsie** [comment]
Can you explain this?
> I use Paper 1.15.2 on a BungeeCord

I don't understand how could you relate BungeeCord with Paper, they doesn't share any information, and all BungeeCord does is to forward the player connection to the backend server, but that's it.

Can you provide me your server startup log (of the server that has Spicord in it)?

**Comment by HackerSte** [comment]
I specified that that server is under a bungeecord network to give you as much detail as possible, and also because in all the servers I have, I have installed BanAnnouncer and AdvancedBan ... Maybe I need to install it in only one?
My startup log: https://pastebin.com/zkwqVtUC

**Comment by OopsieWoopsie** [comment]
Okay, I get it now, but you are not using AdvancedBan properly, if you have a network you should install AdvancedBan ONLY on the BungeeCord server, not on the Spigot (Paper) ones.
Also by using MySQL it doesn't means all AdvancedBan instances will be talking to each other to keep up-to-date, the MySQL storage is just... for storage, if you ban someone in a server, all other AdvancedBan instances will not notice that.

The proper setup for your case is:
Install AdvancedBan on BungeeCord, and for BanAnnouncer (BA) to work you need to put it in the server where the punishment manager is installed, so, on BungeeCord too, and BA requires Spicord so it needs to be on bungee too...

**Comment by HackerSte** [comment]
Now it works!!
Thank you very very much!
Have a great day 😊
