### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by Kapotgegaan** [Spicord/BanAnnouncer#35]
Hai, Iv been working and changing things for a while now but i cant get it to send the discord messages. Can you spot the problem?

here is my console error:

[Sat, 8. May 2021 19:52:35 UTC INFO] Kapotgegaan issued server command: /warn GeLuKsNuMmEr7 test -s
[Sat, 8. May 2021 19:52:35 UTC ERROR] [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[Sat, 8. May 2021 19:52:35 UTC ERROR] [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[Sat, 8. May 2021 19:52:35 UTC WARN] java.lang.NullPointerException
[Sat, 8. May 2021 19:52:35 UTC WARN] at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.entryAdded(LiteBans.java:69)
[Sat, 8. May 2021 19:52:35 UTC WARN] at litebans.cc.b(cc.java:13)
[Sat, 8. May 2021 19:52:35 UTC WARN] at litebans.bQ.run(bQ.java:57)
[Sat, 8. May 2021 19:52:35 UTC WARN] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Sat, 8. May 2021 19:52:35 UTC WARN] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Sat, 8. May 2021 19:52:35 UTC WARN] at java.lang.Thread.run(Thread.java:748)
[Sat, 8. May 2021 19:52:35 UTC INFO] [Silent][9m ‡                                                              ‡
[Sat, 8. May 2021 19:52:35 UTC INFO] Action ➤ Warned
[Sat, 8. May 2021 19:52:35 UTC INFO] Staff Member ➤ (Kapotgegaan)
[Sat, 8. May 2021 19:52:35 UTC INFO] Warned player ➤ (GeLuKsNuMmEr7)
[Sat, 8. May 2021 19:52:35 UTC INFO] Reason ➤ (test)
[Sat, 8. May 2021 19:52:35 UTC INFO] [9m ‡                                                              ‡
[Sat, 8. May 2021 19:52:35 UTC INFO] CONSOLE issued server command: /jail GeLuKsNuMmEr7 warn 15m
[Sat, 8. May 2021 19:52:35 UTC INFO] [TherondiaSMP] Player GeLuKsNuMmEr7 jailed for 15 minutes.
[Sat, 8. May 2021 19:52:38 UTC INFO] Kapotgegaan issued server command: /unwarn GeLuKsNuMmEr7 -s
[Sat, 8. May 2021 19:52:38 UTC ERROR] [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[Sat, 8. May 2021 19:52:38 UTC ERROR] [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[Sat, 8. May 2021 19:52:38 UTC WARN] java.lang.NullPointerException
[Sat, 8. May 2021 19:52:38 UTC WARN] at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.entryRemoved(LiteBans.java:80)
[Sat, 8. May 2021 19:52:38 UTC WARN] at litebans.cc.a(cc.java:14)
[Sat, 8. May 2021 19:52:38 UTC WARN] at litebans.fo.run(fo.java:68)
[Sat, 8. May 2021 19:52:38 UTC WARN] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Sat, 8. May 2021 19:52:38 UTC WARN] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Sat, 8. May 2021 19:52:38 UTC WARN] at java.lang.Thread.run(Thread.java:748)
[Sat, 8. May 2021 19:52:38 UTC INFO] [Silent]Kapotgegaan unwarned GeLuKsNuMmEr7
[Sat, 8. May 2021 19:52:40 UTC INFO] Kapotgegaan issued server command: /unjail GeLuKsNuMmEr7

Thanks alot.

**Comment by OopsieWoopsie** [comment]
Hi, what LiteBans version are you using?

**Comment by Kapotgegaan** [comment]
2.6.11

**Comment by Kapotgegaan** [comment]
[23:00:40] [Server thread/INFO]: [Spicord] Registered addon 'Server Information' (spicord::info) by Sheidy
[23:00:40] [Server thread/INFO]: [Spicord] Registered addon 'Plugin List' (spicord::plugins) by Sheidy
[23:00:40] [Server thread/INFO]: [Spicord] Registered addon 'Player List' (spicord::players) by Sheidy
[23:00:40] [Server thread/INFO]: [Spicord] Registered addon 'BanAnnouncer' (ban_announcer) by Sheidy
[23:00:40] [Server thread/WARN]: [Spicord] Loaded class litebans.api.Events from LiteBans v2.6.11 which is not a depend, softdepend or loadbefore of this plugin.
[23:00:40] [Server thread/INFO]: [BanAnnouncer] [AutoDetect] Using LiteBans as the punishment manager.
[23:00:40] [Server thread/INFO]: [Spicord] Starting the bots...
[23:00:40] [Server thread/INFO]: [Spicord] Starting bot 'TherondiaSMP'.

**Comment by Kapotgegaan** [comment]
iv just seen this could it be that i need to downgrade the litebans?

**Comment by OopsieWoopsie** [comment]
No, you may have a wrong BanAnnouncer configuration, line 69 and 80 calls getConfig(), which I assume may be causing the error

**Comment by Kapotgegaan** [comment]
well. The config is only 54 lines xD

**Comment by Kapotgegaan** [comment]
# The channel(s) id where the messages will be sent
# If you don't know how to get a channel id... https://www.google.com/?q=discord+how+to+get+channel+id
channels-to-announce:
  - 834142756053188618

# If the text is empty (nothing between the double quotes),
#    the message will not be sent (a.k.a. the message is "disabled"), for example:
#
#    kick: "" <-- this will disable the message
#
#    If you don't want to use embed messages you can use pure text, for ex.:
#
#    kick: "The player %player% was kicked by %staff%"
#
#    
# Variables are self-explained...
messages:
  kick:      "{embed:kick}"
  ban:       "{embed:ban}"
  tempban:   "{embed:tempban}"
  mute:      "{embed:mute}"
  tempmute:  "{embed:tempmute}"
  banip:     "{embed:banip}"
  tempbanip: "{embed:tempbanip}"
  warn:      "{embed:warn}"
  tempwarn:  "{embed:tempwarn}"
  unbanip:   "{embed:unbanip}"
  unwarn:    "{embed:unwarn}"
  unmute:    "{embed:unmute}"
  unban:     "{embed:unban}"

# The plugin used for manage the punishments
# Possible values:
#     auto        = Auto detect
#     advancedban = Use AdvancedBan
#     litebans    = Use LiteBans
#     maxbans     = Use MaxBansPlus
punishment-manager: auto

# If it's set to false, the punishments made
#    with the '-s' flag of LiteBans will be sent anyways.
ignore-silent: false

# Name to show when the console does stuff
console-name: "Console"

# When a punishment expires this text will be added to the staff name
# for example:
# "X was unbanned by StaffName (Automatic)"
automatic: "Automatic"

# Do not change this or i'll eat your cookies
config-version: 4

**Comment by Kapotgegaan** [comment]
ow this sucks haha
wait il upload the config

**Comment by Kapotgegaan** [comment]
[config.txt](https://github.com/Spicord/BanAnnouncer/files/6446607/config.txt)

**Comment by Kapotgegaan** [comment]
Ow. Iv just changed nothing and it works right now. Nothing changed just some time went over. But thanks for the help.

**Comment by OopsieWoopsie** [comment]
> well. The config is only 54 lines xD

I was talking about the code, not your config

**Comment by Kapotgegaan** [comment]
oh okay. And you fixt that or? xD

**Comment by OopsieWoopsie** [comment]
> oh okay. And you fixt that or? xD

There's nothing to fix, I was just pointing out what lines were causing the error, and those lines tried to access the config, so I assume the problem came from a bad config.

**Comment by Kapotgegaan** [comment]
Okay. Still thanks alot :D
