### ISSUE TITLE
AdvancedBan Note Support

### ISSUE THREAD

**Issue by kevin4998** [Spicord/BanAnnouncer#36]
# Feature: Advanced Ban /note support

## Background

[Advanced Ban](https://www.spigotmc.org/resources/advancedban.8695/) has an extra command called `/note` which allows staff to put extra information on players. This information is only visible to staff, and is used on our server to provide more information about an event (such as kicking or banning players) which does not fit in the limited space of a single ban or kick command.

## Request

In version **2.2.0** of Ban Announcer there is no support for the /note-feature, therefore, I would like to request if it would be possible to add this as an extra notification?

## Technical Details

Having had a quick look at [LiteBans](https://www.spigotmc.org/resources/litebans.3715/) and [MaxBans](https://dev.bukkit.org/projects/maxbans-plus) it appears those two plugins do not have a similar /note-feature, so this would only be for AdvancedBan. Luckily this note component is just another [`PunishmentType`](https://github.com/DevLeoko/AdvancedBan/blob/master/core/src/main/java/me/leoko/advancedban/utils/PunishmentType.java) for AdvancedBan just like any other ban or kick. Which should make it relatively easy to add currently. Beside `/note` there is also the equivalent `/unnote` to remove previously made notes.

## Closing Notes

It would be nice to have this feature to automate a lot of the (boring) administration behind banning/kicking/etc. . So thanks for the creation of this plugin, it has helped speed things up and make life easier for us!

**Comment by OopsieWoopsie** [comment]
Hi, can you test this build? https://github.com/Spicord/BanAnnouncer/releases/tag/2.2.1
The note.json file will be automatically created when the plugin loads, don't forget to add [this line in your config.yml](https://github.com/Spicord/BanAnnouncer/blob/master/src/main/resources/config.yml#L19)
```
note: "{embed:note}"
```

**Comment by kevin4998** [comment]
Testing completed!

The /note-functionality now works great, it nicely shows in Discord. However /unnote does not properly show. An example message for when I remove a note from `personal_builder` would be:

```
The player `personal_builder` was noted by `Console` for `%reason`
```

It still says `noted` even when we remove it and it also shows `%reason%` instead of the previous reason (this could be because when we remove the note there is no attached reason). But thanks for the quick response and integration!

**Comment by OopsieWoopsie** [comment]
Oh my fault, I have (mis)read in your message that there's no /unnote - so no way to remove notes, that's why I didn't added an unnote.json file.
Will work on that :)

**Comment by OopsieWoopsie** [comment]
Jar file here: https://github.com/Spicord/BanAnnouncer/releases/tag/2.2.1

**Comment by kevin4998** [comment]
Second testing session has completed.

Both commands work and properly show in Discord, however the unnote text looks as follows:

```
A note for `personal_builder` has been removed by `Console`. Note: `%reason%`
```

So the `%reason%` text doesn't get replaced sadly. Also thanks for mentioning about the `unnote` field in the config, I did actually forget that.

**Comment by OopsieWoopsie** [comment]
This seems like an AdvancedBan issue then, I will tell the developer about this

**Comment by OopsieWoopsie** [comment]
(didn't reported this yet as I'm trying to figure out it by myself)
Open your AdvancedBan config file (plugins/AdvancedBan/config.yml) and change the value of "Debug" to "true", that option is located at the end of the config.
Then when you run /unnote, a message like this should appear in your console:
```
[AdvancedBan] Deleted punishment <id> from <player> punishment reason: <reason>
```
if the reason appears empty, then this is actually an AdvancedBan issue and not related to BanAnnouncer.
If the reason appears properly in AdvancedBan's message but in the BanAnnouncer message it stills appear %reason%, then this is a BanAnnouncer issue.

**Comment by kevin4998** [comment]
I tested it on our server and in a minimal test environment. In both cases Advanced Ban (version 2.3.0) shows the reason properly in the debug messages but BanAnnouncer still shows `%reason%`.

**Comment by OopsieWoopsie** [comment]
Hi, I just checked at the code and realised that was the way I made un-punish messages, if you look carefully you will notice that in every un-punish JSON file there's no %reason%, I made it like that because for the current un-punishments at the time (unban, unmute, unwarn) it wasn't necessary to include the reason; in the case of the notes then the thing changes as it is useful to know the original reason of the note that was deleted.
I will make a commit for this tomorrow or in a few days (I just need to change about 2 lines of code but I'm busy...)

**Comment by OopsieWoopsie** [comment]
Hello! it's done :) 

https://github.com/Spicord/BanAnnouncer/releases/tag/2.2.1
