### ISSUE TITLE
BanAnnouncer issue with discord channel ID

### ISSUE THREAD

**Issue by Bartjuh22** [Spicord/BanAnnouncer#39]
Hello Sir,

When i change the channel ID en reload the plugin i am unable to connect the server.
i am recieving the message `"Internal Exception: java.lang.IllegalStateException: zip file closed"`

When i remove the channel id and reload the plugin again it will be working again.

Can you help me with this?

**Comment by OopsieWoopsie** [comment]
Hi ma'am, in order to help you I will need you to send me the *full* error.
