### ISSUE TITLE
cannot find id console.

### ISSUE THREAD

**Issue by friendlyBrandon** [Spicord/BanAnnouncer#42]
[Fri, 18. Jun 2021 11:38:07 UTC WARN] [Spicord] The addon with the id 'Ban_Announcer' was not found.

**Comment by OopsieWoopsie** [comment]
The id is ban_announcer, with lowercase, you put an uppercase B and A

**Comment by friendlyBrandon** [comment]
I changed it
with the lower a and b it is still not found.

**Comment by friendlyBrandon** [comment]
[Fri, 18. Jun 2021 16:12:05 UTC WARN] [Spicord] The addon with the id 'ban_announcer' was not found.
