### ISSUE TITLE
[Fri, 18. Jun 2021 16:12:05 UTC WARN] [Spicord] The addon with the id 'ban_announcer' was not found.

### ISSUE THREAD

**Issue by friendlyBrandon** [Spicord/BanAnnouncer#43]
[Fri, 18. Jun 2021 16:12:05 UTC WARN] [Spicord] The addon with the id 'ban_announcer' was not found.

**Comment by friendlyBrandon** [comment]
18.06 20:10:27 [Server] Server thread/ERROR Error occurred while enabling BanAnnouncer v2.3.0 (Is it up to date?)

**Comment by OopsieWoopsie** [comment]
As I told you in SpigotMC, I need your full server log. And regarding that second message, you didn't sent the whole error, just an useless log line that actually says nothing,

**Comment by friendlyBrandon** [comment]
19.06 01:00:47 [Server] Server thread/INFO Enabling BanAnnouncer v2.3.0
19.06 01:00:47 [Server] Server thread/ERROR Error occurred while enabling BanAnnouncer v2.3.0 (Is it up to date?)
19.06 01:00:47 [Server] INFO java.lang.NoSuchMethodError: 'void org.spicord.SpicordLoader.addStartupListener(org.spicord.event.EventHandler)'
19.06 01:00:47 [Server] INFO at eu.mcdb.ban_announcer.bukkit.BanAnnouncerBukkit.onEnable(BanAnnouncerBukkit.java:40) ~[?:?]
19.06 01:00:47 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Spigot_Latest.jar:3149-Spigot-101ebb6-9122f5a]
19.06 01:00:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[Spigot_Latest.jar:3149-Spigot-101ebb6-9122f5a]
19.06 01:00:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[Spigot_Latest.jar:3149-Spigot-101ebb6-9122f5a]
19.06 01:00:47 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[Spigot_Latest.jar:3149-Spigot-101ebb6-9122f5a]
19.06 01:00:47 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[Spigot_Latest.jar:3149-Spigot-101ebb6-9122f5a]
19.06 01:00:47 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[Spigot_Latest.jar:3149-Spigot-101ebb6-9122f5a]
19.06 01:00:47 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[Spigot_Latest.jar:3149-Spigot-101ebb6-9122f5a]
19.06 01:00:47 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[Spigot_Latest.jar:3149-Spigot-101ebb6-9122f5a]
19.06 01:00:47 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[Spigot_Latest.jar:3149-Spigot-101ebb6-9122f5a]
19.06 01:00:47 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
19.06 01:00:47 [Server] Server thread/INFO Enabling UltimateHomes v2.2
19.06 01:00:47 [Server] Server thread/INFO --------------------------------------
19.06 01:00:47 [Server] Server thread/INFO UltimateHomes by kixmc
19.06 01:00:47 [Server] Server thread/INFO Enabled on version 2.2
19.06 01:00:47 [Server] Server thread/INFO --------------------------------------
19.06 01:00:48 [Server] Server thread/INFO Enabling Votifier v2.7.2
19.06 01:00:48 [Server] Server thread/INFO Loaded token for website: default
19.06 01:00:48 [Server] Server thread/INFO Using epoll transport to accept votes.
19.06 01:00:48 [Server] Server thread/INFO Method none selected for vote forwarding: Votes will not be received from a forwarder.
19.06 01:00:48 [Server] Server thread/INFO Enabling GriefPrevention v16.17.1-2b69191
19.06 01:00:48 [Server] Votifier epoll boss/INFO Votifier enabled on socket /54.38.217.165:5060.
19.06 01:00:48 [Server] Server thread/INFO Finished loading configuration.
19.06 01:00:48 [Server] Server thread/INFO 33 total claims loaded.
19.06 01:00:48 [Server] Server thread/INFO Customizable messages loaded.
19.06 01:00:48 [Server] Server thread/INFO Finished loading data (File Mode).
19.06 01:00:48 [Server] Server thread/INFO Boot finished.
19.06 01:00:48 [Server] Server thread/INFO Enabling dynmap v3.2-beta-1-470
19.06 01:00:49 [Server] Server thread/INFO Added 2 custom biome mappings
19.06 01:00:49 [Server] Server thread/INFO Using LuckPerms 5.3.39 for access control
19.06 01:00:49 [Server] Server thread/INFO Mod Support processing completed
19.06 01:00:49 [Server] Server thread/INFO Loaded 25 shaders.
19.06 01:00:49 [Server] Server thread/INFO Loaded 82 perspectives.
19.06 01:00:49 [Server] Server thread/INFO Loaded 22 lightings.
19.06 01:00:49 [Server] Server thread/INFO Starting enter/exit processing
19.06 01:00:49 [Server] Dynmap Render Thread/INFO Finish marker initialization
19.06 01:00:49 [Server] Server thread/INFO Web server started on address 54.38.217.165:9941
19.06 01:00:49 [Server] Server thread/INFO version 3.2-beta-1-470 is enabled - core version 3.2-beta-1-470
19.06 01:00:49 [Server] Server thread/INFO For support, visit https://reddit.com/r/Dynmap or our Discord at https://discord.gg/s3rd5qn
19.06 01:00:49 [Server] Server thread/INFO To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
19.06 01:00:49 [Server] Server thread/INFO If you'd like to donate, please visit https://www.patreon.com/dynmap or https://ko-fi.com/michaelprimm
19.06 01:00:49 [Server] Server thread/INFO Loaded 3 maps of world 'world'.
19.06 01:00:49 [Server] Server thread/INFO Loaded 2 maps of world 'world_nether'.
19.06 01:00:49 [Server] Server thread/INFO Loaded 2 maps of world 'world_the_end'.
19.06 01:00:49 [Server] Server thread/INFO Enabled
19.06 01:00:49 [Server] Server thread/INFO Enabling Spartan vBuild 413.1
19.06 01:00:50 [Server] Startup Done loading 257KB of data to the Search Engine.
19.06 01:00:50 [Server] pool-12-thread-1/INFO (IL:GET) Failed to connect to the Spartan Cloud.
19.06 01:00:50 [Server] pool-12-thread-1/INFO Error: Index 0 out of bounds for length 0
19.06 01:00:50 [Server] pool-12-thread-1/INFO In Depth: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
19.06 01:00:50 [Server] Server thread/INFO Enabling VotingPlugin v6.4
19.06 01:00:50 [Server] Server thread/INFO Giving VotingPlugin.Player permission by default, can be disabled in the config
19.06 01:00:50 [Server] Server thread/INFO Enabled VotingPlugin 6.4
19.06 01:00:50 [Server] Server thread/INFO Enabling Webvotelogger v1.0
19.06 01:00:50 [Server] Server thread/INFO Web Vote logger by abhiram loaded
19.06 01:00:50 [Server] Server thread/INFO Enabling SuperVanish v6.2.6
19.06 01:00:50 [Server] Server thread/INFO Please install ProtocolLib to be able to use all SuperVanish features: https://www.spigotmc.org/resources/protocollib.1997/
19.06 01:00:50 [Server] Server thread/INFO Hooked into dynmap
19.06 01:00:50 [Server] Server thread/INFO Enabling SmoothTimber v1.17.0
19.06 01:00:50 [Server] Server thread/INFO SmoothTimber || You're currently using the supported Minecraft Version 1.17 (Core v1_16x)
19.06 01:00:51 [Server] Server thread/INFO Enabling DiscordSRV v1.23.0
19.06 01:00:51 [Server] Server thread/INFO Enabling Admin-GUI v1.4.8
19.06 01:00:51 [Server] Server thread/INFO Server permissions file permissions.yml is empty, ignoring it
19.06 01:00:51 [Server] Startup Done (19.452s)! For help, type "help"
19.06 01:00:51 [Server] Craft Scheduler Thread - 5/INFO UPDATE FOUND: A newer version of sleep-most is available to download!
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO ----------------------------------------------
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO +===============+
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO | SkinsRestorer |
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO |---------------|
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO |  Bukkit only  |
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO +===============+
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO ----------------------------------------------
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO Current version: 14.0.2
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO This is the latest version!
19.06 01:00:51 [Server] Craft Scheduler Thread - 1/INFO ----------------------------------------------
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO []=====[Enabling AdminGUI]=====[]
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO | Information:
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |   Name: AdminGUI
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |   Developer: Black1_TV
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |   Version: 1.4.8 (FREE)
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |   Premium: https://rabbit-company.com
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO | Support:
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |   Discord: Crazy Rabbit#0001
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |   Mail: ziga.zajc007@gmail.com
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |   Discord: https://discord.gg/hUNymXX
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO |
19.06 01:00:51 [Server] Craft Scheduler Thread - 0/INFO []=====================================[]
19.06 01:00:51 [Server] pool-39-thread-1/INFO DiscordSRV is up-to-date. (ae26c8fa7a85120ccb1cf9bc46d8de316c1a5db8)
19.06 01:00:51 [Server] DiscordSRV - Initialization/INFO [JDA] Login Successful!
19.06 01:00:51 [Server] JDA MainWS-ReadThread/INFO [JDA] Connected to WebSocket
19.06 01:00:52 [Server] JDA MainWS-ReadThread/INFO [JDA] Finished Loading!
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO Found server G:RebelCraft(829762298553040916)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:moderator-only(842724447596183553)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:rules(842724447596183552)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:ticket-0011(854375062065119232)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:ticket-0013(855032537806012436)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:all-members-39(830934351326871552)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:members-30(830934354234441759)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:bots-9(830934357426307153)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:‼welcome‼(830782192917151766)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:📢announcements📢(830781844429471774)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:📣giveways📣(841192592112484362)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:✴server-website✴(845333630401904640)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:🗣general-chat🗣(829762298553040919)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:⚡vip-chat🎃(855504925396303924)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:📁server-log📁(830534982135971920)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:🌏dynmap-website🌏(840968489933733928)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:ticket(840290156824756264)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:👥server-voting👥(835629148436561970)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:👀serverip👀(830781378068217856)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:👑vip-kit👑(841732574853988393)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:🎶music-channel🎶(842073345066532895)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:🧍♀memes🧍♀(830931447673127002)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:ingame-trading-channel(837938642533351474)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:🦗bugs🦗(831241049279299614)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:suggestions(831242506372251659)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:💟donations💟(833316582142771221)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:🛠community-buildings🛠(836849534423924736)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:streams(840570570039099392)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:create-giveway-channel(841294103425187921)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:banned-players(854726319006810142)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:emojis(854814900903346215)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:staff-chat-💫(830932843236556860)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO - TC:spam-console(847105513846210631)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO Console forwarding assigned to channel TC:spam-console(847105513846210631)
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO Enabling SuperVanish hook
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO Enabling dynmap hook
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO Enabling LuckPerms hook
19.06 01:00:52 [Server] DiscordSRV - Initialization/INFO No chat plugin hooks enabled
19.06 01:00:55 [Server] Server thread/WARN Failed to hook into vault economy
19.06 01:00:55 [Server] Server thread/WARN Failed to hook into vault permissions
19.06 01:00:56 [Server] Server thread/WARN Can't keep up! Is the server overloaded? Running 5142ms or 102 ticks behind
19.06 01:01:01 [Server] Craft Scheduler Thread - 6/INFO VotingPlugin is up to date! Version: 6.4
19.06 01:01:06 [Server] Craft Scheduler Thread - 2/INFO A new version is available!
19.06 01:01:06 [Server] Craft Scheduler Thread - 2/INFO Current version you're using: 5.5
19.06 01:01:06 [Server] Craft Scheduler Thread - 2/INFO Latest version available: 5.5.1
19.06 01:01:06 [Server] Craft Scheduler Thread - 2/INFO [AdvancedTeleport] Download link: https://www.spigotmc.org/resources/advanced-teleport.64139/
19.06 01:01:12 [Server] Server thread/INFO Registered addon 'Server Information' (spicord::info) by Sheidy
19.06 01:01:12 [Server] Server thread/INFO Registered addon 'Plugin List' (spicord::plugins) by Sheidy
19.06 01:01:12 [Server] Server thread/INFO Registered addon 'Player List' (spicord::players) by Sheidy
19.06 01:01:12 [Server] Server thread/INFO Starting the bots...
19.06 01:01:12 [Server] Server thread/INFO Starting bot 'default'.
19.06 01:01:13 [Server] ForkJoinPool.commonPool-worker-19/INFO [JDA:JDA] Login Successful!
19.06 01:01:13 [Server] ForkJoinPool.commonPool-worker-19/WARN The addon with the id 'ban_announcer' was not found.
19.06 01:01:13 [Server] JDA MainWS-ReadThread/INFO [JDA:WebSocketClient] Connected to WebSocket
19.06 01:01:13 [Server] JDA MainWS-ReadThread/INFO [JDA:JDA] Finished Loading!
19.06 01:01:44 [Server] Server thread/INFO There are 0 of a max of 60 players online: 
19.06 01:01:53 [Server] Dynmap Render Thread/INFO Loading default resource pack
19.06 01:01:54 [Server] Dynmap Render Thread/WARN Resource assets/minecraft/textures/block/moss_carpet.png for mod minecraft not found

**Comment by friendlyBrandon** [comment]
think that is enough, when it started up for the plugin till the line.

**Comment by OopsieWoopsie** [comment]
You need Spicord 4.0.0 as noted on the plugin update, you are using an old Spicord version.

**Comment by friendlyBrandon** [comment]
AH THAT IS WHYXD
