### ISSUE TITLE
When changing someone's ban reason to update in discord too

### ISSUE THREAD

**Issue by thiagogebrim13** [Spicord/BanAnnouncer#46]
Sometimes I get something wrong with banning someone and in discord it's still wrong the reason if I change

**Comment by OopsieWoopsie** [comment]
Hi, the /change-reason command does not notify other plugins that a reason has changed, it just updates the entry on the database and that's it, nothing more happens. And BanAnnouncer can't know if that happened as B.A. only processes *new* (un-)punishments, and a reason change is not any kind of (un-)punishment. 
Just be more careful when writing reasons :(
