### ISSUE TITLE
[Feature Request] LibertyBans support

### ISSUE THREAD

**Issue by D3adhkwen** [Spicord/BanAnnouncer#48]
I would like to suggest adding LibertyBans support for this plugin.

Link: https://github.com/A248/LibertyBans

**Comment by OopsieWoopsie** [comment]
Sure! this is also good because I can now add Velocity support for BanAnnouncer ^^ I have not done that before because it would be useless to make it work on Velocity if there wasn't any punishment plugin that had an API that this plugin can work with -_-

**Comment by D3adhkwen** [comment]
Looking forward to it!

**Comment by D3adhkwen** [comment]
any updates on this?

**Comment by OopsieWoopsie** [comment]
> any updates on this?

Yes, I have already (pre-)implemented this last week, I plan to make other changes on the BanAnnouncer code before pushing the support for LibertyBans.

**Comment by OopsieWoopsie** [comment]
Update: I was going to push the changes but before I wanted to make a test build, so... I made it but realised that LibertyBans is compiled for Java 11, and BanAnnouncer is for Java 8, so I can't make a build unless I change the minimum required Java version for BanAnnouncer, which is a thing that would bring many "issues" (not actual issues, but people complaining...), so I will now look for other ways in doing this without requiring BanAnnouncer to use Java 11

**Comment by OopsieWoopsie** [comment]
Finished :) will make a release soon

**Comment by OopsieWoopsie** [comment]
Released.
https://github.com/Spicord/BanAnnouncer/releases/tag/2.4.0

Put the "libertybans-ext_1.0.jar" file into the "plugins/BanAnnouncer/extensions" folder (it is created automatically at startup, but you can create it yourself before starting the server)

Enjoy :+1:
