### ISSUE TITLE
when unban sends 2 messages at once

### ISSUE THREAD

**Issue by LtAkmal** [Spicord/BanAnnouncer#51]
[Image 1](https://cdn.discordapp.com/attachments/869491836023103489/871437723733458944/Screenshot_2021-08-01_234920.png)
[Image 2](https://cdn.discordapp.com/attachments/869491836023103489/871437725759320084/Screenshot_2021-08-01_235733.png)

**Comment by OopsieWoopsie** [comment]
If you are using LiteBans, then it is likely that LiteBans is triggering the unban event two times - it's a LiteBans bug (I can't do anything about it), if you are NOT USING LiteBans, then please send your server log.
