### ISSUE TITLE
The addon BanAnnouncer (ban_announcer) does not implement the onShutdown() method

### ISSUE THREAD

**Issue by YourMayskiy** [Spicord/BanAnnouncer#54]
[08:20:48 WARN]: [Spicord] The addon BanAnnouncer (ban_announcer) does not implement the onShutdown() method

**Comment by OopsieWoopsie** [comment]
Hello, you should not worry about this, I also think I should have never created that warning message :sweat: it is not even neccesary

**Comment by OopsieWoopsie** [comment]
Update: I implemented the method, it was indeed necessary, sorry for closing the issue.
