### ISSUE TITLE
Ban Announcer Addon Key

### ISSUE THREAD

**Issue by HackInstalled** [Spicord/BanAnnouncer#55]
Hey there! 

What is the addon key for this? i did the "ban_announcer" and it cannot find it.
I am running Spicord 4.0.0 and the current version of this addon.

My preferred way of contact is: Installed#0001 on discord.

Thanks!

![image](https://user-images.githubusercontent.com/83131727/132018343-f2c99371-a3ae-483c-966f-3d53045877bb.png)

**Comment by OopsieWoopsie** [comment]
Hi, I will need you to send me your full server startup log

**Comment by HackInstalled** [comment]
> Hi, I will need you to send me your full server startup log

Could you DM me: Installed#0001 as i do not check github too often

**Comment by OopsieWoopsie** [comment]
Sorry, but I will only give support through GitHub
