### ISSUE TITLE
Plugin Error Version 2.3.0

### ISSUE THREAD

**Issue by TheNiCraftGHG** [Spicord/BanAnnouncer#56]
Version: 2.3.0
I have the punishplugin Advancedban installed on a paper 1.16.5 Server
Wehn I run the command the plugin will be red an in the console the error will be come when the plugin start.

Console Log:
05.09 13:30:15 [Server] ERROR Error occurred while enabling BanAnnouncer v2.3.0 (Is it up to date?)
05.09 13:30:15 [Server] INFO java.lang.NoSuchMethodError: org.spicord.SpicordLoader.addStartupListener(Lorg/spicord/event/EventHandler;)V
05.09 13:30:15 [Server] INFO at eu.mcdb.ban_announcer.bukkit.BanAnnouncerBukkit.onEnable(BanAnnouncerBukkit.java:40) ~[?:?]
05.09 13:30:15 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-783]
05.09 13:30:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-783]
05.09 13:30:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-783]
05.09 13:30:15 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-783]
05.09 13:30:15 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-783]
05.09 13:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-783]
05.09 13:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-783]
05.09 13:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-783]
05.09 13:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-783]

**Comment by OopsieWoopsie** [comment]
You need the latest version of Spicord, it seems that you are using an old Spicord version.
