### ISSUE TITLE
Triple announce

### ISSUE THREAD

**Issue by TheOnne** [Spicord/BanAnnouncer#57]
Hello! Whenever i ban or kick or whatever do in discord that ban spams 3 times.
Here link if you can see.
https://prnt.sc/1rr6hti

**Comment by OopsieWoopsie** [comment]
Hi, this issue have been reported a lot of times, and is not because of this addon, is because of LiteBans. And as I'm not the LiteBans developer, I can't do anything about this. Sorry.

**Comment by TheOnne** [comment]
I don't have litebans i have advancedbans

**Comment by OopsieWoopsie** [comment]
Hi, I will need you to provide me the full server log. The server needs to be running and this issue should be present, I don't need a clean log as it will be useless to trace this problem.
