### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Jurikkkk** [Spicord/BanAnnouncer#64]
hi i can't run i don't know how i put it in the folder but i don't know how please help me

**Comment by OopsieWoopsie** [comment]
Sorry but I can't help you if you do not provide enough information about your problem

**Comment by Jurikkkk** [comment]
I need this I have downloaded everything and the plugin inserted into the addons folder but only from now on I don't know how to proceed and I don't understand the instructions on the spigot page I just want an exact file from you on what to do

**Comment by Jurikkkk** [comment]
exact procedure* sorry

**Comment by OopsieWoopsie** [comment]
> I need this I have downloaded everything and the plugin inserted into the addons folder but only from now on I don't know how to proceed and I don't understand the instructions on the spigot page I just want an exact file from you on what to do

You should not put this plugin into the addons folder, it need to be into the "plugins" folder, just like any other normal plugin
