### ISSUE TITLE
What am i overlooking?

### ISSUE THREAD

**Issue by kylewbird** [Spicord/BanAnnouncer#65]
I have tried a few times, started even with a clean installation and somehow, even though I follow the instructions, I seem to be overlooking something. In game spicord status shows ready, the bot is on the discord server and online, the channel id is correct. but I still get no message from ban announcer.. Please help?

**Comment by OopsieWoopsie** [comment]
Hi, I would like to know if you solved the problem :thinking:

**Comment by kylewbird** [comment]
Good day, yes, managed to get it sorted. Tried the entire setup again but only installed on the proxy server, did the exact same configs. And poof it works. Thanks for getting back to me.
