### ISSUE TITLE
(Velocity) AdvancedBan 2.4.0 Support

### ISSUE THREAD

**Issue by Boy0000** [Spicord/BanAnnouncer#66]
Trying to set up so that AdvancedBan actions are sent to our Discord Channel, but it seemingly does not work.
When I leave `punishment-manager: auto` i get this error:
![image](https://user-images.githubusercontent.com/62521371/143495013-5c2ab38f-b7f3-413f-9e93-8acda4b8f397.png)

When specifying AdvancedBan I get no error, but it does not work either. Same thing if I set it to LiteBans (which I do not have on the server).

**Comment by OopsieWoopsie** [comment]
Does the same problem persists with AdvancedBan 2.3.0 (the latest release) ?

**Comment by Boy0000** [comment]
AdvancedBan only have Velocity support on their development branch and version 2.4.0.
Bungee probably wont have issues, but looking at the code I could not find any listener for AdvancedBan under velocity, only LibertyBans

**Comment by OopsieWoopsie** [comment]
The Velocity support will likely be removed before the code on the development branch gets released, as there are a lot of bugs and no maintainer for it :( .
So I don't think I should make a Velocity listener for AdvancedBan, unless Velocity support becomes part of the next releases of AdvancedBan.

**Comment by Boy0000** [comment]
From talking to the devs it seems they will not be maintaining Velocity support.
