### ISSUE TITLE
Ban announcer is not recognized

### ISSUE THREAD

**Issue by ROKA611** [Spicord/BanAnnouncer#69]
When i start spicord, it says nothing about addon ban announcer
[Spicord] Enabling Spicord v4.1.2
[Loader] Loaded library 'toml4j-0.7.2.jar'
[Loader] Loaded library 'JDA-4.2.1.jar'
[Loader] Loaded library 'rhino-1.7.12.jar'
[Loader] Loaded library 'snakeyaml-1.26.jar'
[Spicord] Loaded 1 bots, 0 disabled.
[Spicord] Spicord will load in 10 seconds
[Spicord] Registered addon 'Server Information' (spicord::info) by Sheidy
[Spicord] Registered addon 'Plugin List' (spicord::plugins) by Sheidy
[Spicord] Registered addon 'Player List' (spicord::players) by Sheidy
[Spicord] Starting the bots...
[Spicord] Starting bot 'default'.
[Spicord] Loaded class net.dv8tion.jda.api.JDABuilder from SimpleStaffChat v1.6.4.1 which is not a depend, softdepend or loadbefore of this plugin.

this is what my config looks like for spicord

[[bots]]
  name = "default"
  enabled = true
  token = "REDACTED"
  command_support = true
  command_prefix = "-"
  addons = [
    "spicord::info",
    "spicord::plugins",
    "spicord::players",
	"ban_announcer"

**Comment by OopsieWoopsie** [comment]
Closed in favor of the SpigotMC conversation.
