### ISSUE TITLE
Error with BanAnnouncer and LibertyBans on Velocity

### ISSUE THREAD

**Issue by Kay313** [Spicord/BanAnnouncer#73]
Hello, I get this error when trying to launch BanAnnouncer and LibertyBans on Velocity

Logs:
https://paste.gg/p/anonymous/2ddf6cf316204320a72445d9819f8ee0

Plugins:
https://paste.gg/p/anonymous/27e2d4f041c4437d98c9c8c97667cf67

**Comment by D3adhkwen** [comment]
Facing the same issue here. LibertyBans API changed in 1.0.0 release, hope the developers can fix this soon.

**Comment by anvorgesa** [comment]
Officialy released 2.6.0 including this fix.
https://github.com/Spicord/BanAnnouncer/releases/tag/2.6.0

**Comment by Turjoy9** [comment]
Hello. @anvorgesa , after updating I'm getting this error on my console https://paste.gg/p/anonymous/d4a4f00ff58e471dab921a0d922c4dab/revisions. using latest spicord, banannouncer and libertybans. velocity version 3.1.4 build 114

**Comment by anvorgesa** [comment]
@Turjoy9 that error is not related with this issue. It seems like you have something misconfigured, please ensure you have followed all configuration steps for both Spicord and BanAnnouncer.

**Comment by D3adhkwen** [comment]
> Hello. @anvorgesa , after updating I'm getting this error on my console https://paste.gg/p/anonymous/d4a4f00ff58e471dab921a0d922c4dab and it doesn't pass the message to discord. using latest spicord, banannouncer and libertybans. velocity version 3.1.4 build 114

I am also getting this issue. Player name also becomes <Unknown> if it is a Composite Ban, which is added in LibertyBans 1.0.0. BanAnnouncer does not support BanAnnouncer fully yet.

**Comment by anvorgesa** [comment]
@D3adhkwen 
> I am also getting this issue.

Are you sure? because `java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null` has nothing to do with LibertyBans.

> BanAnnouncer does not support BanAnnouncer fully yet.

Hmm...

**Comment by D3adhkwen** [comment]
I had issue with `java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null` before.. that magically fixed itself.
> BanAnnouncer does not support BanAnnouncer fully yet.

Sorry, I meant BanAnnouncer does not support LibertyBans 1.0.0+ fully yet.
The image below shows a composite ban on discord.
![image](https://user-images.githubusercontent.com/38313757/158140691-6b155703-01e1-4b64-a492-36dd4eb9b6b3.png)
