### ISSUE TITLE
[BanAnnouncer]: [AutoDetect] No compatible plugin found. BanAnnouncer will not work!.

### ISSUE THREAD

**Issue by ArjanSchoorl** [Spicord/BanAnnouncer#75]
When using BanAnnouncer with Spicord it won't recognize Litebans as a compatible plugin. I have tried to change it in the config with auto or litebans. But none worked. I included both logs with a fresh restart.

Log auto: https://bin.bloom.host/dopalewago
Log litebans: https://bin.bloom.host/pofojemesu
Config auto: https://mcpaste.io/d9d7077e4d9f8c29
Config litebans: https://mcpaste.io/ffd04e3bedcc9672

**Comment by anvorgesa** [comment]
LiteBans support is only for BungeeCord and Spigot, not for Velocity
