### ISSUE TITLE
3$ premium version w/o branding (or customizeable)

### ISSUE THREAD

**Issue by hirata-estate** [Spicord/BanAnnouncer#79]
![image](https://user-images.githubusercontent.com/61897277/161067973-a7c52795-2f8e-4466-8a30-dc50a7aa8fd9.png)
I heavily dislike having branding like this, and this'll allow that for those who want it, and should help you offset the time you spend on this plugin.

**Comment by anvorgesa** [comment]
That's not branding, that's a default value that is easily changeable like every other text on the messages... seems like you skipped the tutorial part where it says to customize the files as you please.
