### ISSUE TITLE
How to install BanAnnouncer on just one server and have it broadcast synced banned/kick notification from others server that are synced on litebans SQL

### ISSUE THREAD

**Issue by TypicalShavonne** [Spicord/BanAnnouncer#83]

**Comment by anvorgesa** [comment]
MySQL is not a "linking" solution, neither a real-time comunication solution, it is just a database, and you know what databases are for? for storing data and accessing it later, that's it, there's absolutely **no way** for BanAnnouncer to know when a punishment ocurred on another server.
You will need to use BanAnnouncer (+LiteBans +Spicord) **only** on BungeeCord for achieving what you asked for.
