### ISSUE TITLE
BanAnnouncer not detecting LiteBans on Velocity

### ISSUE THREAD

**Issue by saboooor** [Spicord/BanAnnouncer#88]
![image](https://user-images.githubusercontent.com/42164502/170187195-80bef87c-73ee-4116-a275-95194d6b8d62.png)
LiteBans is installed as well as BanAnnouncer and Spicord on velocity-3.1.2-SNAPSHOT-139

**Comment by anvorgesa** [comment]
That's exactly as expected, there isn't any BanAnnouncer release that supports LiteBans on Velocity.

**Comment by anvorgesa** [comment]
Included this in the lastest release.
