### ISSUE TITLE
BanAnnouncer not showing thumbnail for tempmute/mute

### ISSUE THREAD

**Issue by Pabsb** [Spicord/BanAnnouncer#89]
Embed for discord is not showing image thumbnail only for Mutes / tempmutes

Shows up perfectly fine in https://leovoel.github.io/embed-visualizer/ the code below but in discord it doesn't show the thumbnail. Shows it for ban/tempban/ipban/tempipban/warn etc but just not for mutes and temp mutes.
````
{
  "embed": {
    "title": "Temp Mute",
    "description": "Player: `%player%`\n Temp muted by: `%staff%`\n Reason: `%reason%`\n Duration: `%duration%`",
    "color": 16741235,
    "thumbnail": {
    "url": "https://i.imgur.com/9a59cGg.png"
    }
  }
}
````

**Comment by anvorgesa** [comment]
Hello, please send me the mute.json & ban.json files into a .zip archive, so I can have the original file of the one that does not work and the other that does work, I can't debug it if you just copy&paste the file contents, I need the original files.

**Comment by Pabsb** [comment]
[Ban_and_mute_json.zip](https://github.com/Spicord/BanAnnouncer/files/8820862/Ban_and_mute_json.zip)

**Comment by anvorgesa** [comment]
Interesting, try using a different image for the mute embed, it is *probably* not displayed because Discord thinks it may be inappropriate :thinking: happened a lot to me with parrot images, Discord thinks they are NSFW.

**Comment by anvorgesa** [comment]
First link loads nothing inside Discord, but in the browser it does :woman_shrugging: 
![image](https://user-images.githubusercontent.com/95182588/172017846-18473412-d107-4ebb-893c-36aec7131b48.png)

Just use a different image then
