### ISSUE TITLE
Litebans Error

### ISSUE THREAD

**Issue by Chiquis2005** [Spicord/BanAnnouncer#95]
17:51:24 [INFO]  ‡                                                              ‡
 Acción ➤ Baneado
 Staff ➤ (Chiquis20056)
 jugador ➤ (TheChok)
 Razón ➤ (Chiteando!)
 ‡                                                              ‡
17:51:24 [SEVERE] [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
17:51:24 [SEVERE] java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.

17:51:24 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)

17:51:24 [SEVERE]     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)

17:51:24 [SEVERE]     at com.mysql.cj.jdbc.result.ResultSetImpl.first(ResultSetImpl.java:617)

17:51:24 [SEVERE]     at litebans.bJ.first(bJ.java)

17:51:24 [SEVERE]     at eu.mcdb.ban_announcer.listener.LiteBansListener.getPlayerName(LiteBansListener.java:119)

17:51:24 [SEVERE]     at eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:81)

17:51:24 [SEVERE]     at eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)

17:51:24 [SEVERE]     at litebans.a2.b(a2.java:13)

17:51:24 [SEVERE]     at litebans.cA.run(cA.java:57)

17:51:24 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

17:51:24 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

17:51:24 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)

17:51:24 [SEVERE] [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
17:51:24 [SEVERE] java.lang.IllegalStateException: Couldn't fetch player name from UUID '98a5d993-a9a8-3cf0-993c-03973094ea4b'. The message was not sent.

17:51:24 [SEVERE]     at eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:84)

17:51:24 [SEVERE]     at eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)

17:51:24 [SEVERE]     at litebans.a2.b(a2.java:13)

17:51:24 [SEVERE]     at litebans.cA.run(cA.java:57)

17:51:24 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

17:51:24 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

17:51:24 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by anvorgesa** [comment]
https://github.com/Spicord/BanAnnouncer/issues/94#issuecomment-1200024631
