### ISSUE TITLE
Warn annoucement failing to send

### ISSUE THREAD

**Issue by Firav** [Spicord/BanAnnouncer#97]
Howdy!

Upon using /warn within LiteBans, an error is displayed in console and no Discord message for punishment type warn is sent.

[02:48:20 INFO]: Firav issued server command: /warn DeanGulberry More platonic warnings!
[02:48:20 INFO]: [BanAnnouncer] [STDOUT] Message is null, ignoring it.
[02:48:20 WARN]: Nag author(s): '[OopsieWoopsie]' of 'BanAnnouncer' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[02:48:20 INFO]: Firav warned DeanGulberry for 'More platonic warnings!'

Screenshot:
![Screenshot](http://img.firav.us/images/2022/08/22/cmd_2022-08-22_22-55-08.png)

Versions:
BanAnnouncer 2.6.3 (post #94 hotfix)
Spicord 4.2.2
LiteBans 2.10.3
Paper 131 (1.19.2 - 2da891f)

**Comment by anvorgesa** [comment]
Hello, it could be because:

1. You have disabled warn notifications in the config by emptying the "warn" string; or
2. You have a bad formatted warn.json file and so it failed to load

**Comment by Firav** [comment]
> Hello, it could be because:
> 
>     1. You have disabled warn notifications in the config by emptying the "warn" string; or
> 
>     2. You have a bad formatted warn.json file and so it failed to load

The warn notification is enabled for "{embed:warn}" and the json does not throw exceptions when being parsed.
I've also reset the warn.json back to factory, still having the same results.

**Comment by anvorgesa** [comment]
Have you restarted the server after you deleted the old warn.json file?

**Comment by Firav** [comment]
Yes. The plugin generates a new default, and still does not function.

**Comment by anvorgesa** [comment]
Make a backup of your current BanAnnouncer configuration and then delete the `plugins > BanAnnouncer` folder entirely (with the server off), let the plugin regenerate it (start the server) and then configure your channel in BA's config, make a warning and see if it appears on Discord.

This is to see if this is an internal issue with the plugin or if it was caused by a configuration.

**Comment by Firav** [comment]
Followed your instructions, and functionality resumed. I'll have to look into the configuration issue. Thank you for the help!
