### ISSUE TITLE
[PunishControl Support]

### ISSUE THREAD

**Issue by SideLo98** [Spicord/BanAnnouncer#98]
Support for PunishControl https://www.spigotmc.org/resources/%E2%9B%8F%EF%B8%8Fpunishcontrol%E2%84%A2-powerful-all-in-one-punishment-system-1-12-1-17.94741/

**Comment by anvorgesa** [comment]
Hello, it seems that it does not have a developer api with events, and even if it had, I would not be able to add support to it as I do not own a license for that (premium) plugin.
