### ISSUE TITLE
No me funciona con LiteBans en BungeeCord.

### ISSUE THREAD

**Issue by pamacinco** [Spicord/BanAnnouncer#99]
08:32:49 [SEVERE] [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
08:32:49 [SEVERE] java.lang.LinkageError: loader constraint violation: loader net.md_5.bungee.api.plugin.PluginClassloader @df4b72 wants to load interface net.dv8tion.jda.api.JDA. A different interface with the same name was previously loaded by net.md_5.bungee.api.plugin.PluginClassloader @2baa8d82. (net.dv8tion.jda.api.JDA is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @2baa8d82, parent loader 'app')

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:120)

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102)

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:108)

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryRemoved(LiteBansListener.java:149)

08:32:49 [SEVERE]     at litebans.g1.b(g1.java:14)

08:32:49 [SEVERE]     at litebans.ib.run(ib.java:68)

08:32:49 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

08:32:49 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

08:32:49 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:831)

08:32:49 [SEVERE] java.lang.LinkageError: loader constraint violation: loader net.md_5.bungee.api.plugin.PluginClassloader @df4b72 wants to load interface net.dv8tion.jda.api.JDA. A different interface with the same name was previously loaded by net.md_5.bungee.api.plugin.PluginClassloader @2baa8d82. (net.dv8tion.jda.api.JDA is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @2baa8d82, parent loader 'app')

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:120)

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102)

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:108)

08:32:49 [SEVERE]     at eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)

08:32:49 [SEVERE]     at litebans.g1.a(g1.java:13)

08:32:49 [SEVERE]     at litebans.cs.run(cs.java:57)

08:32:49 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

08:32:49 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

08:32:49 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by anvorgesa** [comment]
Hola, el error es seguramente porque estas usando otro plugin (a parte de Spicord) el cual tambien tiene algun tipo de funcionalidad de Discord.
